---

- name: cli tools
  pacman: name={{ item }} state=latest
  with_items:
    - tmux
    - the_silver_searcher
    - jq
    - inotify-tools
    - openssh

- yaourt: name=fzf-git state=latest
  become: yes
  become_user: "{{ user }}"

- include: zsh.yml
  tags: [zsh]
- include: neovim.yml
  tags: [nvim, neovim]
- include: ranger.yml
- include: basher.yml
- include: weechat.yml
- include: mutt.yml
