---

- include: bash.yml

- name: cli tools
  pacman: name={{ item }} state=latest
  with_items:
    - tmux
    - the_silver_searcher
    - jq
    - inotify-tools
    - openssh
    - fzf

- include: neovim.yml
  tags: [nvim, neovim]
- include: ranger.yml
- include: weechat.yml
- include: mutt.yml
