---
- name: install zsh
  pacman: name=zsh state=present

- name: zplug
  git:
    repo: "https://github.com/b4b4r07/zplug.git"
    dest: "/home/{{ user }}/.zplug"
  become: yes
  become_user: "{{ user }}"

- name: remove bashrc
  file: path={{ item }} state=absent
  with_items:
    - /home/{{ user }}/.bashrc
    - /home/{{ user }}/.bash_profile
