---

- hosts: localhost
  vars_files:
  - vars/ansible.yml
  - vars/user.yml
  - vars/secrets.yml

  tasks:
  - name: update pacman cache
    pacman: update_cache=yes

  - name: install core packages
    pacman: name={{ item }}
    with_items:
    - sudo
    - zip
    - unzip
    - curl
    - wget
    - gnupg

  - import_tasks: network.yml
  - import_tasks: sudoers.yml
  - import_tasks: user.yml
