---

- hosts: localhost
  vars_files:
    - vars/ansible.yml
    - vars/user.yml
    - vars/secrets.yml

  roles:
    - role: core
      tags: [core]

    - role: user
      tags: [user]

    - role: desktop
      tags: [user, desktop]

    - role: apps
      tags: [user, apps]
