---

- name: link bash files
  file: src=/usr/src/dotfiles/{{ item }} dest=/home/{{ user }}/.{{ item }} state=link
  with_items:
    - bash
    - bashrc
  become: yes
  become_user: "{{ user }}"
  tags: [dotfiles]

- name: fetch basher
  git:
    repo: "https://github.com/basherpm/basher.git"
    dest: "/home/{{ user }}/.basher"
  become: yes
  become_user: "{{ user }}"
