---

- yaourt: name=yank state=latest
  become: yes
  become_user: "{{ user }}"

- file:
    path: /usr/src/clipster
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"

- name: download clipster
  git:
    repo: "https://github.com/mrichar1/clipster.git"
    dest: "/usr/src/clipster"
    update: no
  become: yes
  become_user: "{{ user }}"
  notify:
    - restart clipster

- file: src=/usr/src/clipster/clipster dest=/usr/local/bin/clipster state=link
  notify:
    - restart clipster

- name: clipster ini
  file: src=/usr/src/dotfiles/clipster dest=/home/{{ user }}/.config/clipster state=link
  become: yes
  become_user: "{{ user }}"
  notify:
    - restart clipster
  tags: [dotfiles]

- name: clipster service
  copy:
    src: clipster.service
    dest: /home/{{ user }}/.config/systemd/user/clipster.service
  notify:
    - restart clipster
  become: yes
  become_user: "{{ user }}"

# doing this manually :(
# https://github.com/ansible/ansible-modules-core/issues/1479
#- service: name=clipster enabled=yes state=started user=yes
#  become: yes
#  become_user: "{{ user }}"
