---
- name: install display manager
  pacman: name={{ item }} state=present
  with_items:
    - rxvt-unicode
    - i3-wm
    - i3status
    - dmenu
    - polkit

- name: setup .xinitrc
  copy: src=xinitrc dest=/home/{{ user }}/.xinitrc owner={{ user }} group={{ user }}

- name: x configs
  copy: src={{ item }} dest=/home/{{ user }}/.{{ item }} owner={{ user }} group={{ user }}
  with_items:
    - Xresources
    - Xdefaults

- name: i3 config directories
  file: dest=/home/{{ user }}/.config/{{ item }} state=directory owner={{ user }} group={{ user }}
  with_items:
    - i3
    - i3status

- name: i3 config files
  copy: src={{ item }} dest=/home/{{ user }}/.config/{{ item }}/config owner={{ user }} group={{ user }}
  with_items:
    - i3
    - i3status

- name: startx on login
  copy: src=zlogin dest=/home/{{ user }}/.zlogin
