---
- name: install display manager
  pacman: name={{ item }} state=present
  with_items:
    - rxvt-unicode
    - i3-wm
    - i3status
    - dmenu

- name: setup .xinitrc
  copy: src=xinitrc dest=/home/{{ user }}/.xinitrc owner={{ user }} group={{ user }}

- name: setup x configs
  copy: src={{ item }} dest=/home/{{ user }}/.{{ item }} owner={{ user }} group={{ user }}
  with_items:
    - Xresources
    - Xdefaults

- name: setup i3 configs
  copy: src=i3 dest=/home/{{ user }}/.config/i3/config owner={{ user }} group={{ user }}
