---
- name: install display manager
  pacman: name={{ item }} state=present
  with_items:
    - rxvt-unicode
    - i3-wm
    - i3status
    - dmenu
    - feh

- name: x configs
  copy: src={{ item }} dest=/home/{{ user }}/.{{ item }} owner={{ user }} group={{ user }}
  with_items:
    - xinitrc
    - Xresources

- name: i3 config directories
  file: dest=/home/{{ user }}/.config/{{ item }} state=directory owner={{ user }} group={{ user }}
  with_items:
    - i3
    - i3status

- name: i3 config files
  copy: src={{ item }} dest=/home/{{ user }}/.config/{{ item }}/config owner={{ user }} group={{ user }}
  with_items:
    - i3
    - i3status

- name: startx on login
  copy: src=zlogin dest=/home/{{ user }}/.zlogin

- name: default wallpaper
  copy: src=wallpaper.jpg dest=/home/{{ user }}/Pictures/wallpaper.jpg force=no owner={{ user }} group={{ user }}

- name: fehbg script
  copy: src=fehbg.sh dest=/home/{{ user }}/.fehbg force=no owner={{ user }} group={{ user }}
