---

- file:
    path: /usr/src/dotfiles
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"

- name: clone dotfiles
  git:
    repo: "https://github.com/dylanmei/dotfiles.git"
    dest: /usr/src/dotfiles
    update: no
  become: yes
  become_user: "{{ user }}"
