---

- name: install emacs
  pacman: name=emacs state=latest

- name: create emacs.d directory
  file: dest=/home/{{ user }}/.emacs.d state=directory
  become: yes
  become_user: "{{ user }}"
  tags: [dotfiles]

- name: link emacs configs
  file: src=/usr/src/dotfiles/emacs.d/{{ item }} dest=/home/{{ user }}/.emacs.d/init.el state=link
  with_items:
    - init.el
  become: yes
  become_user: "{{ user }}"
  tags: [dotfiles]
