---
- name: install git
  pacman: name=git state=present

- name: gitconfig
  template: src=gitconfig.j2 dest=/home/{{ user }}/.gitconfig owner={{ user }} group={{ user }}

- name: gitignore
  copy: src=files/gitignore dest=/home/{{ user }}/.gitignore owner={{ user }} group={{ user }}

