---
- include: user.yml

- name: home folders
  file: path=/home/{{ user }}/{{ item }} state=directory owner={{ user }} group={{ user }}
  with_items:
    - Downloads
    - Pictures

- include: git.yml
- include: fonts.yml
  tags:
    - desktop
- include: dm.yml
  tags:
    - i3
    - desktop
- include: bindkeys.yml
  tags:
    - desktop
