---
- include_vars: secrets.yml

- name: ensure main user
  user:
    name: "{{ user }}"
    groups: users,wheel
    password: "{{ password }}"
    createhome: yes
    home: "/home/{{ user }}"
    shell: /usr/bin/zsh
    generate_ssh_key: no

- name: ensure user directories
  file:
    path: /home/{{ user }}/{{ item }}
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0755
    state: directory
  with_items:
    - .config
    - src

- name: zshrc
  copy: src=files/zshrc dest=/home/{{ user }}/.zshrc owner={{ user }} group={{ user }}

- name: gitconfig
  template: src=gitconfig.j2 dest=/home/{{ user }}/.gitconfig owner={{ user }} group={{ user }}

- name: gitignore
  copy: src=files/gitignore dest=/home/{{ user }}/.gitignore owner={{ user }} group={{ user }}
