---

- include: user.yml
- include: git.yml

- name: home folders
  file: path=/home/{{ user }}/{{ item }} state=directory
  with_items:
    - Downloads
    - Pictures
    - src
    - .config/systemd/user
    - .config/systemd/scripts
  become: yes
  become_user: "{{ user }}"

