---

- include: user.yml
- include: gpg.yml

- name: home folders
  file: path=/home/{{ user }}/{{ item }} state=directory
  with_items:
    - .config
    - Downloads
    - Pictures
    - src
  become: yes
  become_user: "{{ user }}"

- include: dotfiles.yml
- include: bash.yml
- include: git.yml
- include: neovim.yml

- copy: src=yaourtrc dest=/home/{{ user }}/.yaourtrc
  become: yes
  become_user: "{{ user }}"

- name: cli tools
  pacman: name={{ item }} state=latest
  with_items:
    - tmux
    - the_silver_searcher
    - jq
    - inotify-tools
    - openssh
    - fzf

- include: ranger.yml
- include: weechat.yml
- include: mutt.yml

- name: install xorg packages
  pacman: name={{ item }} state=present
  with_items:
    - xorg-server
    - xorg-xinit
    - xorg-xrdb
    - xorg-xfontsel
    - xorg-xev
    - xorg-xprop
    - xorg-xrandr
    - polkit
    - xsel
    - xclip

- name: link xinitrc
  file: src=/usr/src/dotfiles/xinitrc dest=/home/{{ user }}/.xinitrc state=link mode=0755
  become: yes
  become_user: "{{ user }}"

- yaourt: name=yank state=latest
  become: yes
  become_user: "{{ user }}"

- include: touchpad.yml
- include: pulseaudio.yml
- include: fonts.yml
- include: hyperterm.yml
- include: bspwm.yml
- include: rofi.yml
- include: dunst.yml
