---

- name: ensure main user
  user:
    name: "{{ user }}"
    groups: users,wheel
    password: "{{ password }}"
    createhome: yes
    home: "/home/{{ user }}"
    shell: /usr/bin/zsh
    generate_ssh_key: no

- name: ensure user directories
  file:
    path: /home/{{ user }}/{{ item }}
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0755
    state: directory
  with_items:
    - .config
    - src

- name: ensure sudo
  copy:
    dest: /etc/sudoers.d/{{ user }}
    content: "{{ user }} ALL=(ALL) ALL"
    mode: 0440
    owner: root
    group: root

- include: git.yml
- include: shell.yml
  tags: ["shell"]
- include: neovim.yml
- include: fonts.yml
- include: dm.yml
