---

- include: user.yml
- include: gpg.yml

- name: home folders
  file: path=/home/{{ user }}/{{ item }} state=directory
  with_items:
    - .config
    - Downloads
    - Pictures
    - src
  become: yes
  become_user: "{{ user }}"

- include: dotfiles.yml
- include: bash.yml
- include: git.yml
- include: neovim.yml

- copy: src=yaourtrc dest=/home/{{ user }}/.yaourtrc
  become: yes
  become_user: "{{ user }}"

- name: cli tools
  pacman: name={{ item }} state=latest
  with_items:
    - tmux
    - the_silver_searcher
    - jq
    - inotify-tools
    - openssh
    - fzf

- include: ranger.yml
- include: weechat.yml
- include: mutt.yml
