---

- include: user.yml

- name: home folders
  file: path=/home/{{ user }}/{{ item }} state=directory
  with_items:
    - .config
    - .segreti
    - Downloads
    - Pictures
    - src
  become: yes
  become_user: "{{ user }}"

- copy: src=yaourtrc dest=/home/{{ user }}/.yaourtrc
  become: yes
  become_user: "{{ user }}"

- name: install git
  pacman: name=git state=latest

- include: dotfiles.yml
  tags: [dotfiles]

- name: git dotfiles
  file: src=/usr/src/dotfiles/{{ item }} dest=/home/{{ user }}/.{{ item }} state=link
  with_items:
    - gitignore
    - gitconfig
  become: yes
  become_user: "{{ user }}"
  tags: [dotfiles]
