---
- name: install zsh
  pacman: name=zsh state=present

- name: zshrc
  copy: src=files/zshrc dest=/home/{{ user }}/.zshrc owner={{ user }} group={{ user }}

- name: remove bashrc
  file: path={{ item }} state=absent
  with_items:
    - /home/{{ user }}/.bashrc
    - /home/{{ user }}/.bash_profile

- name: install tools
  pacman: name={{ item }} state=present
  with_items:
    - fzf
    - the_silver_searcher
    #- fasd
