---
- name: install zsh
  pacman: name=zsh state=present

- name: zshrc
  copy: src=files/zshrc dest=/home/{{ user }}/.zshrc owner={{ user }} group={{ user }}

- name: zpm
  git:
    repo: "https://github.com/horosgrisa/zpm.git"
    dest: "/home/{{ user }}/.zpm"
  become_user: "{{ user }}"

- name: remove bashrc
  file: path={{ item }} state=absent
  with_items:
    - /home/{{ user }}/.bashrc
    - /home/{{ user }}/.bash_profile

- name: install tools via pacman
  pacman: name={{ item }} state=present
  with_items:
    - fzf
    - the_silver_searcher

- name: install tools via cower
  cower: name={{ item }} state=present
  become_user: "{{ user }}"
  with_items:
    - fasd
