---
- name: install zsh
  pacman: name=zsh state=present

- name: zshrc
  copy: src=files/zshrc dest=/home/{{ user }}/.zshrc
  become: yes
  become_user: "{{ user }}"

- name: zsh directory
  file: dest=/home/{{ user }}/.zsh state=directory
  become: yes
  become_user: "{{ user }}"

- name: zsh scripts
  copy: src=files/{{ item }} dest=/home/{{ user }}/.zsh/{{ item }}
  with_items:
    - aliases.zsh
    - history.zsh
  become: yes
  become_user: "{{ user }}"

- name: zplug
  git:
    repo: "https://github.com/b4b4r07/zplug.git"
    dest: "/home/{{ user }}/.zplug"
  become: yes
  become_user: "{{ user }}"

- name: install tools via pacman
  pacman: name={{ item }} state=present
  with_items:
    - fzf
    - the_silver_searcher

- name: install tools via cower
  cower: name={{ item }} state=present
  become_user: "{{ user }}"
  with_items:
    - fasd

- name: remove bashrc
  file: path={{ item }} state=absent
  with_items:
    - /home/{{ user }}/.bashrc
    - /home/{{ user }}/.bash_profile

