---

- name: setup i3wm environment
  pacman: name={{ item }} state=present
  with_items:
    - i3-wm
    - i3status
    - wmctrl
    - dmenu
    - rofi
    - arandr
    - feh
    - compton

- name: link Xresources
  file: src=/usr/src/dotfiles/Xresources dest=/home/{{ user }}/.Xresources state=link
  become: yes
  become_user: "{{ user }}"
  tags: [dotfiles]

- name: link i3 dotfiles
  file: src=/usr/src/dotfiles/{{ item }} dest=/home/{{ user }}/.config/{{ item }} state=link
  with_items:
    - i3
    - i3status
  become: yes
  become_user: "{{ user }}"
  tags: [dotfiles]

- name: link i3 exec scripts
  file: src=/usr/src/dotfiles/{{ item }}.sh dest=/home/{{ user }}/.{{ item }} state=link
  with_items:
    - fehbg
    - xrandr
  become: yes
  become_user: "{{ user }}"
  tags: [dotfiles]

- name: link rofi scripts
  file: src=/usr/src/dotfiles/{{ item }}.sh dest=/usr/local/bin/{{ item }} state=link
  with_items:
    - rofi-quit
    - rofi-windows
  tags: [dotfiles]

- name: default wallpaper
  copy: src=wallpaper.jpg dest=/home/{{ user }}/Pictures/wallpaper.jpg force=no
  become: yes
  become_user: "{{ user }}"

- include: termite.yml

- name: link compton.conf
  file: src=/usr/src/dotfiles/compton.conf dest=/home/{{ user }}/.compton.conf state=link
  tags: [dotfiles]

- name: link gtk configs
  file: src=/usr/src/dotfiles/gtk-3.0 dest=/home/{{ user }}/.config/gtk-3.0 state=link
  tags: [dotfiles]
