---

- name: install xorg packages
  pacman: name={{ item }} state=present
  with_items:
    - xf86-video-intel
    - xorg-server
    - xorg-xinit
    - xorg-xrdb
    - xorg-xfontsel
    - xorg-xev
    - xorg-xprop
    - xorg-xrandr
    - polkit

- include: touchpad.yml
- include: clipboard.yml
  tags: [clipboard]
- include: fonts.yml
- include: dm.yml
- include: bindkeys.yml
