---

- name: install xorg packages
  pacman: name={{ item }} state=present
  with_items:
    - xorg-server
    - xorg-xinit
    - xorg-xrdb
    - xorg-xfontsel
    - xorg-xev
    - xorg-xprop
    - xorg-xrandr
    - polkit
    - xsel
    - xclip

- include: touchpad.yml
- include: pulseaudio.yml
- include: clipboard.yml
  tags: [clipboard]
- include: fonts.yml
- include: dm.yml
- include: bspwm.yml
- include: rofi.yml
- include: dunst.yml
#- include: screenshot.yml
