---
- name: install drivers
  pacman: name={{ item }} state=present
  with_items:
    - xf86-video-intel
    - xf86-input-synaptics

- name: install xorg packages
  pacman: name={{ item }} state=present
  with_items:
    - xorg-server
    - xorg-xinit
    - xorg-xrdb
    - xorg-xfontsel
    - xorg-xev

- name: touchpad config
  copy: src=synaptics.conf dest=/etc/X11/xorg.conf.d/50-synaptics.conf
