---
- name: install network packages
  pacman: name={{ item }} state=present
  with_items:
    - netctl
    - wpa_supplicant
    - dialog

- name: define network profiles
  template: src=netctl/Home.j2 dest=/etc/netctl/Home
