---

- name: update pacman cache
  pacman: update_cache=yes

- name: install reflector
  pacman: name=reflector state=present

- stat: path=/etc/pacman.d/mirrorlist
  register: mirrorlist

- name: update mirrorlist
  command: reflector --country "United States" -l 200 -p http --sort rate --save /etc/pacman.d/mirrorlist
  when: "{{ mirrorlist.stat.mtime }} < {{ ansible_date_time.epoch|int - (60 * 60 * 24) }}"

- name: update package list
  command: pacman -Syy --noconfirm

- name: update all packages
  command: pacman -Su --noconfirm
  when: update_all_packages is defined
