#!/usr/bin/env zsh

PATH=/usr/local/sbin:/usr/local/bin:/usr/bin

source ~/.zplug/zplug

zplug "b4b4r07/enhancd", of:enhancd.sh
zplug "zsh-users/zsh-completions"
zplug "horosgrisa/zsh-history-substring-search"
#zplug "zsh-users/zsh-history-substring-search"
zplug "zsh-users/zsh-syntax-highlighting", nice:19

zplug "mafredri/zsh-async"
zplug "~/.zsh/zsh-pure", from:local

if ! zplug check; then
  zplug install
fi

zplug load

[[ -f /etc/profile.d/fzf.zsh ]] && source /etc/profile.d/fzf.zsh

bindkey -e
source ~/.zsh/aliases.zsh
source ~/.zsh/history.zsh
