#!/usr/bin/env zsh

PATH=/usr/local/sbin:/usr/local/bin:/usr/bin

source ~/.zplug/zplug

zplug "horosgrisa/zsh-history-substring-search"
#zplug "zsh-users/zsh-history-substring-search"
zplug "b4b4r07/enhancd", of:enhancd.sh
zplug "zsh-users/zsh-syntax-highlighting"
zplug "kasperisager/zsh-pure"

if ! zplug check; then
  zplug install
fi

zplug load

#eval $(fasd --init auto)
source /etc/profile.d/fzf.zsh

bindkey -e
source ~/.zsh/aliases.zsh
source ~/.zsh/history.zsh
