#!/usr/bin/env zsh

HISTFILE=~/.zsh_history
SAVEHIST=8192
PATH=/usr/local/sbin:/usr/local/bin:/usr/bin
bindkey -e
source ~/.zplug/zplug

zplug "horosgrisa/zsh-history-substring-search"
zplug "zsh-users/zsh-syntax-highlighting"
zplug "kasperisager/zsh-pure"

if ! zplug check; then
  zplug install
fi

zplug load

alias vim="nvim"
alias tree="tree -C"

#eval $(fasd --init auto)
. /etc/profile.d/fzf.zsh
