---

#- pacman: name={{ item }} state=latest
#  with_items:
#    - gtk3
#    - gconf
#    - gvfs
#    - xdg-utils
#    - libnotify
#    - libxss
#    - hunspell-en

- name: chat apps
  yaourt: name={{ item }} state=present
  with_items:
    - slack-desktop
    - hipchat
  become: yes
  become_user: "{{ user }}"
