---

- name: vmware dependencies
  pacman: name={{ item }} state=latest
  with_items:
    - fuse
    - gtkmm
    - net-tools
    - linux-headers

# gpg --recv-keys F7E48EDB
- name: more vmware dependecies
  yaourt: name={{ item }} state=latest
  with_items:
    - vmware-ovftool
    - ncurses5-compat-libs
    - vmware-systemd-services
  become: yes
  become_user: "{{ user }}"

# - download vmware workstation
# - patch for newer linux kernels
#   # Step 1: Extract source
#   tar xvf /usr/lib/vmware/modules/source/{vmmon,vmnet}.tar
#
#   # Step 2: Patch source -- overly specific match so we don't accidentally double-patch
#   # You could also use vim to change get_user_pages to get_user_pages_remote
#   sed -i 's/get_user_pages(/get_user_pages_remote(/' vmmon-only/linux/hostif.c vmnet-only/userif.c
#
#   # Step 3: Replace source
#   tar cvf /usr/lib/vmware/modules/source/vmmon.tar vmmon-only
#   tar cvf /usr/lib/vmware/modules/source/vmnet.tar vmnet-only
#
#   # Step 4: Rebuild
#   sudo vmware-modconfig --install-all --console
